services:
  alpha-horizon-backend:
    build: ./backend
    container_name: alpha-horizon-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - alpha-horizon-network

  alpha-horizon-frontend:
    build: ./frontend
    container_name: alpha-horizon-frontend
    restart: unless-stopped
    depends_on:
      - alpha-horizon-backend
    networks:
      - alpha-horizon-network
      - adam

  mongodb:
    image: mongo:latest
    container_name: alpha-horizon-db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - alpha-horizon-network

networks:
  alpha-horizon-network:
    driver: bridge
  adam:
    external: true

volumes:
  mongodb_data:
